version: "2"
services:
  petclinic:
    build: petclinic
    ports:
      - 8080:8080
    logging:
      driver: json-file
      options:
        labels: container_name
    labels:
      container_name: petclinic
  jenkins:
    image: jenkins:latest
    ports:
      - 8081:8080
    logging:
      driver: json-file
      options:
        labels: container_name
    labels:
      container_name: jenkins
  elasticsearch:
    image: elasticsearch:5.2.0
  kibana:
    image: kibana:5.2.0
    ports:
      - 5601:5601
  filebeat:
    build: filebeat
    volumes:
      - /var/lib/docker/containers:/containers
    logging:
      driver: syslog
